using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Marines.Nuke;

[GenerateTypedNameReferences]
public sealed partial class RMCNukeWindow : DefaultWindow
{
    public TimeSpan Time;
    public bool NukingTime;
    public bool Ticking;
    public bool Authenticated;
    public RMCNukeWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        var time = IoCManager.Resolve<IGameTiming>().CurTime;
        base.FrameUpdate(args);

        var displayTime = Time;

        if (Ticking)
            displayTime = Time - time;

        NukeTimer.Text = NukingTime ? $"[bold]Detonation Timer: {displayTime:mm\\:ss} Minutes" : $"[bold]Decryption Timer: {displayTime:mm\\:ss} Minutes";
    }

}
