using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Marines.Nuke;

[GenerateTypedNameReferences]
public sealed partial class RMCNukeButton : Control
{
    public bool Status;

    public RMCNukeButton()
    {
        RobustXamlLoader.Load(this);
    }
}
